//constants for GET all appointments
export const GET_ALL_APPOINTMENTS_REQUEST = "GET_ALL_APPOINTMENTS_REQUEST";
export const GET_ALL_APPOINTMENTS_SUCCESS = "GET_ALL_APPOINTMENTS_SUCCESS";
export const GET_ALL_APPOINTMENTS_FAILURE = "GET_ALL_APPOINTMENTS_FAILURE";

//constant for DELETE appointments
export const DELETE_APPOINTMENT_REQUEST = "DELETE_APPOINTMENT_REQUEST";
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_FAILURE = "DELETE_APPOINTMENT_FAILURE";

//constant for CONFIRM appointments
export const CONFIRM_APPOINTMENT_REQUEST = "CONFIRM_APPOINTMENT_REQUEST";
export const CONFIRM_APPOINTMENT_SUCCESS = "CONFIRM_APPOINTMENT_SUCCESS";
export const CONFIRM_APPOINTMENT_FAILURE = "CONFIRM_APPOINTMENT_FAILURE";
