//constants for GET all appointments
export const GET_ALL_APPOINTMENTS_REQUEST = "GET_ALL_APPOINTMENTS_REQUEST";
export const GET_ALL_APPOINTMENTS_SUCCESS = "GET_ALL_APPOINTMENTS_SUCCESS";
export const GET_ALL_APPOINTMENTS_FAILURE = "GET_ALL_APPOINTMENTS_FAILURE";
